"""
Explainable Planning Agent + TOC Bottleneck Analysis  (v3.27)
═══════════════════════════════════════════════════════════════════════

Synthesizes IE/OR + ERP + AI: turns the black-box outputs of MRP-II
(v3.25.10) and CLSP heuristic (v3.26) into **human-readable explanations**
of planning decisions.

Three pillars:

  1. **Demand Provenance Graph** (data lineage)
     Every planned_order_release has a causal chain:
       SO → MPS → MRP gross → MRP net → planned release → BOM child →
       child's planned release → ... → raw material PO
     This module traces and presents the chain.
     Reference: Cheney, Chiticariu & Tan (2009) — provenance in databases.

  2. **TOC Bottleneck Analysis** (Goldratt 1984, 1990)
     Identifies binding work-center constraints from v3.26's CRP load.
     Five-step focusing process:
       (1) IDENTIFY bottleneck     — highest utilization WC
       (2) EXPLOIT it              — schedule it for maximum throughput
       (3) SUBORDINATE non-bottlenecks
       (4) ELEVATE the constraint  — add capacity (overtime, alt WC)
       (5) REPEAT once removed

  3. **Counterfactual Sensitivity** (what-if)
     Given an increment Δ to a parameter (capacity, lead-time, batch size),
     compute the marginal effect on planning outcome.
     Reference: Saltelli et al. (2008) Global Sensitivity Analysis.

──────────────────────────────────────────────────────────────────────
LEGAL / 法律說明
──────────────────────────────────────────────────────────────────────
This module produces **explanatory and advisory analysis** of plans
generated by the IE/OR algorithms (v3.25.10 + v3.26). Its outputs:

  • Identify *probable* root causes of planned orders based on the
    data lineage in the database AT TIME OF QUERY. The actual causal
    chain may differ if data has been edited.
  • Suggest TOC interventions based on Goldratt's framework, which is
    a heuristic philosophy (not a proven theorem). Implementations
    may not achieve theoretical maximum throughput improvement.
  • Counterfactual sensitivity is computed under the same deterministic
    assumptions as v3.25.10/v3.26 — does NOT model stochastic effects.
  • LLM-formatted explanations are generated using a large language
    model and may contain errors. **Always verify against the raw
    numeric data** before acting on conclusions.

To the maximum extent permitted by applicable law, erpilot assumes no
liability for business decisions made based on these explanations.

本模組產生**解釋性與建議性分析**。輸出僅基於資料庫於查詢時點之 lineage；
TOC 建議源自 Goldratt 啟發式框架；敏感度分析沿用 v3.25.10/v3.26 之
確定性假設；LLM 格式化解釋可能含錯誤，**請以原始數值資料為準**。
詳見 docs/PLANNING_EXPLAINABILITY_DESIGN_ZH.md §6。
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.product import BOMItem, Product
from app.models.inventory import Part, Inventory
from app.models.production import (
    ProductionOrder, WorkCenter, Routing, RoutingStep,
)
from app.models.crm_sales import SalesOrder, SalesOrderItem
from app.models.mps_mrp import MpsMaster, MpsEntry, MrpMaster, MrpItem


# ════════════════════════════════════════════════════════════════════
# Data structures: causal explanation tree
# ════════════════════════════════════════════════════════════════════

@dataclass
class ExplanationNode:
    """A single node in the demand provenance tree.

    node_type ∈ {sales_order, mps_entry, mrp_item, bom_explosion}
    """
    node_type: str
    entity_id: str
    label: str  # human-readable
    qty: float
    period: Optional[str] = None
    detail: Dict = field(default_factory=dict)
    children: List["ExplanationNode"] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "node_type": self.node_type,
            "entity_id": self.entity_id,
            "label": self.label,
            "qty": self.qty,
            "period": self.period,
            "detail": self.detail,
            "children": [c.to_dict() for c in self.children],
        }

    def render_tree(self, depth: int = 0) -> str:
        """ASCII tree visualization. Useful for debugging and CLI output."""
        prefix = "  " * depth + ("└─ " if depth > 0 else "")
        line = f"{prefix}[{self.node_type}] {self.label} (qty={self.qty:g}"
        if self.period:
            line += f", period={self.period}"
        line += ")"
        out = [line]
        for c in self.children:
            out.append(c.render_tree(depth + 1))
        return "\n".join(out)


# ════════════════════════════════════════════════════════════════════
# Module 1: Demand Provenance — explain a planned order's "why"
# ════════════════════════════════════════════════════════════════════

async def explain_planned_order(
    db: AsyncSession,
    mrp_item_id: str,
    max_depth: int = 5,
) -> ExplanationNode:
    """Trace upstream from a planned MrpItem to its root demand causes.

    Walks back through:
      MRP item → its parent product's planned releases
                 → that product's MPS entries
                 → optionally any SOs linking to MPS entries

    Returns a tree rooted at the queried MrpItem; children = direct causes.

    Cycle protection: max_depth limits recursion.

    Complexity: O(D · F) where D = max_depth, F = avg fan-in.
    """
    item = (await db.execute(
        select(MrpItem).where(MrpItem.id == mrp_item_id)
    )).scalar_one_or_none()
    if item is None:
        return ExplanationNode(
            node_type="error",
            entity_id=mrp_item_id,
            label=f"MrpItem 不存在 / not found: {mrp_item_id}",
            qty=0,
        )

    # Load the Part for human-readable label
    part = (await db.execute(
        select(Part).where(Part.id == item.part_id)
    )).scalar_one_or_none()
    part_label = (
        f"{part.part_no} ({part.name})" if part
        else f"Part:{item.part_id[:8]}"
    )

    root = ExplanationNode(
        node_type="mrp_item",
        entity_id=item.id,
        label=f"📦 {part_label}",
        qty=item.planned_order_release,
        period=item.period,
        detail={
            "gross_requirement": item.gross_requirement,
            "net_requirement": item.net_requirement,
            "projected_on_hand": item.projected_on_hand,
            "bom_level": item.bom_level,
            "order_type": item.order_type,
        },
    )

    if max_depth <= 0:
        return root

    # Step 1: Find parent products whose BOM uses this part
    # (i.e., who triggered this part's gross requirement)
    parent_bom_items = (await db.execute(
        select(BOMItem).where(
            BOMItem.part_id == item.part_id,
            BOMItem.is_active == True,
        )
    )).scalars().all()

    parent_product_ids = {bom.product_id for bom in parent_bom_items}

    if not parent_product_ids:
        # Top-level part (no parent) — link to MPS directly
        mps_node = await _explain_via_mps(db, item.part_id, item.period, item.mrp_master_id)
        if mps_node:
            root.children.append(mps_node)
        return root

    # Step 2: For each parent product, find its planned releases in the same MRP
    parents_explained = []
    for prod_id in parent_product_ids:
        parent_part = (await db.execute(
            select(Part).where(Part.part_no.in_(
                # use part_no == product_no convention
                select(Product.product_no).where(Product.id == prod_id)
            ))
        )).scalar_one_or_none()
        if parent_part is None:
            continue

        # Find the parent's planned release in the same MRP master
        parent_mrp = (await db.execute(
            select(MrpItem).where(
                MrpItem.mrp_master_id == item.mrp_master_id,
                MrpItem.part_id == parent_part.id,
            )
        )).scalar_one_or_none()
        if parent_mrp is None:
            continue

        # Recurse
        sub = await explain_planned_order(db, parent_mrp.id, max_depth - 1)
        # Annotate the edge: this child uses N units per parent
        bom_link = next(
            (b for b in parent_bom_items if b.product_id == prod_id),
            None
        )
        if bom_link:
            sub.detail["link_qty_per"] = bom_link.qty_per
            sub.detail["link_scrap_rate"] = bom_link.scrap_rate
            sub.label = (
                f"⬆ 因為要做 {sub.label}（每件用 {bom_link.qty_per:g}, "
                f"耗損 {(bom_link.scrap_rate or 0):.1%}）"
            )
        parents_explained.append(sub)

    root.children.extend(parents_explained)

    # If no parents found via BOM, fallback to MPS direct link
    if not parents_explained:
        mps_node = await _explain_via_mps(db, item.part_id, item.period, item.mrp_master_id)
        if mps_node:
            root.children.append(mps_node)

    return root


async def _explain_via_mps(
    db: AsyncSession, part_id: str, period: str, mrp_master_id: str,
) -> Optional[ExplanationNode]:
    """Find MPS entries that might have caused this part's demand."""
    # First, find the Product corresponding to this part (by part_no == product_no)
    part = (await db.execute(
        select(Part).where(Part.id == part_id)
    )).scalar_one_or_none()
    if part is None:
        return None
    product = (await db.execute(
        select(Product).where(Product.product_no == part.part_no)
    )).scalar_one_or_none()
    if product is None:
        return None

    # Find MPS master for this run
    mrp = (await db.execute(
        select(MrpMaster).where(MrpMaster.id == mrp_master_id)
    )).scalar_one_or_none()
    if mrp is None:
        return None

    mps_entries = (await db.execute(
        select(MpsEntry).where(
            MpsEntry.mps_master_id == mrp.mps_master_id,
            MpsEntry.product_id == product.id,
        )
    )).scalars().all()

    if not mps_entries:
        return None

    mps_node = ExplanationNode(
        node_type="mps_entry_set",
        entity_id=mrp.mps_master_id,
        label=f"📋 MPS：{product.product_no} ({product.name})",
        qty=sum(e.planned_production for e in mps_entries),
        period=period,
        children=[
            ExplanationNode(
                node_type="mps_entry",
                entity_id=e.id,
                label=f"📆 期間 {e.period}",
                qty=e.planned_production,
                period=e.period,
                detail={
                    "forecast_demand": e.forecast_demand,
                    "actual_demand": e.actual_demand,
                    "available_to_promise": e.available_to_promise,
                },
            )
            for e in mps_entries
        ],
    )
    return mps_node


# ════════════════════════════════════════════════════════════════════
# Module 2: TOC Bottleneck Analysis  (Goldratt 1984, 1990)
# ════════════════════════════════════════════════════════════════════

@dataclass
class BottleneckReport:
    """Per-WC bottleneck assessment."""
    work_center_id: str
    work_center_code: str
    peak_utilization: float
    peak_period_idx: int
    avg_utilization: float
    is_bottleneck: bool  # peak_util > BOTTLENECK_THRESHOLD
    elevation_options: List[str] = field(default_factory=list)
    shadow_price_minutes: float = 0.0  # gain from +1 min capacity

    def to_dict(self) -> dict:
        return {
            "work_center_id": self.work_center_id,
            "work_center_code": self.work_center_code,
            "peak_utilization": self.peak_utilization,
            "peak_period_idx": self.peak_period_idx,
            "avg_utilization": self.avg_utilization,
            "is_bottleneck": self.is_bottleneck,
            "elevation_options": self.elevation_options,
            "shadow_price_minutes": self.shadow_price_minutes,
        }


# TOC threshold per Schragenheim & Ronen (1990): utilization > 0.85 begins
# to compound delay via Kingman's formula effects (queueing theory).
BOTTLENECK_UTILIZATION_THRESHOLD = 0.85


def identify_bottlenecks_from_loads(loads, work_centers_dict) -> List[BottleneckReport]:
    """Given CRP loads from v3.26, identify bottleneck work-centers.

    TOC five-focusing-steps applied:
      (1) Identify constraint        ← this function
      (2) Exploit                    ← elevation_options suggestion
      (3) Subordinate                ← caller's responsibility (scheduling)
      (4) Elevate                    ← counterfactual_capacity()
      (5) Repeat

    Args:
      loads: List[WorkCenterLoad] from capacity_aware_mrp
      work_centers_dict: {wc_id → WorkCenter ORM object}

    Returns:
      List[BottleneckReport] sorted by peak_utilization descending.
    """
    # Group by work-center
    by_wc: Dict[str, list] = {}
    for L in loads:
        by_wc.setdefault(L.work_center_id, []).append(L)

    reports: List[BottleneckReport] = []
    for wc_id, wc_loads in by_wc.items():
        wc = work_centers_dict.get(wc_id)
        if wc is None:
            continue

        utilizations = [L.utilization for L in wc_loads]
        peak_idx = max(range(len(utilizations)), key=lambda i: utilizations[i])
        peak_util = utilizations[peak_idx]
        avg_util = sum(utilizations) / max(1, len(utilizations))

        is_bn = peak_util > BOTTLENECK_UTILIZATION_THRESHOLD

        # Elevation options per Goldratt 1984 step (4)
        elevation = []
        if is_bn:
            elevation.append(
                f"加班：本 WC 尖峰利用率 {peak_util:.1%} "
                f"於期間 {peak_idx}，可考慮加班或第三班"
            )
            if wc.alternate_group:
                elevation.append(
                    f"使用替代機台群 {wc.alternate_group}"
                )
            elevation.append(
                "外包：部分工序外發第三方加工"
            )
            elevation.append(
                f"購買 / 升級機台（資本決策）— 若年化超載則 ROI 可成立"
            )

        # Shadow price: marginal throughput gain from +1 min capacity
        # Heuristic: at overload, every +1 min directly produces 1 more
        # min of output (linear region). Below capacity, shadow price = 0.
        shadow_price = 1.0 if is_bn else 0.0

        reports.append(BottleneckReport(
            work_center_id=wc_id,
            work_center_code=wc.code,
            peak_utilization=peak_util,
            peak_period_idx=peak_idx,
            avg_utilization=avg_util,
            is_bottleneck=is_bn,
            elevation_options=elevation,
            shadow_price_minutes=shadow_price,
        ))

    reports.sort(key=lambda r: -r.peak_utilization)
    return reports


async def identify_bottlenecks(
    db: AsyncSession, mps_id: str,
) -> Tuple[List[BottleneckReport], "CapacityPlanResult"]:
    """High-level: run capacity-aware MRP, then identify bottlenecks.

    Returns (reports, full_capacity_result).
    """
    from app.services.capacity_aware_mrp import run_capacity_aware_mrp

    capacity_result = await run_capacity_aware_mrp(db, mps_id)

    wcs = (await db.execute(
        select(WorkCenter).where(WorkCenter.is_active == True)
    )).scalars().all()
    wc_dict = {wc.id: wc for wc in wcs}

    reports = identify_bottlenecks_from_loads(capacity_result.loads, wc_dict)
    return reports, capacity_result


# ════════════════════════════════════════════════════════════════════
# Module 3: Counterfactual Sensitivity
# ════════════════════════════════════════════════════════════════════

@dataclass
class CounterfactualResult:
    """Diff between baseline and modified scenario."""
    scenario_name: str
    baseline_overload_count: int
    modified_overload_count: int
    baseline_infeasible_count: int
    modified_infeasible_count: int
    holding_cost_delta: float
    summary: str

    def to_dict(self) -> dict:
        return {
            "scenario_name": self.scenario_name,
            "baseline_overload_count": self.baseline_overload_count,
            "modified_overload_count": self.modified_overload_count,
            "baseline_infeasible_count": self.baseline_infeasible_count,
            "modified_infeasible_count": self.modified_infeasible_count,
            "holding_cost_delta": self.holding_cost_delta,
            "summary": self.summary,
        }


async def counterfactual_capacity_increase(
    db: AsyncSession,
    mps_id: str,
    work_center_id: str,
    multiplier: float = 1.2,  # +20%
) -> CounterfactualResult:
    """What if we increased work-center X's capacity by `multiplier`?

    Per Saltelli et al. (2008): this is local sensitivity analysis;
    a one-factor-at-a-time (OAT) perturbation.

    Limitations:
      • OAT misses interactions (Saltelli §2.5); for global SA see
        Sobol indices.
      • Capacity increase modeled as a single-period change; reality
        is more nuanced (training cost, ramp-up time).

    Returns CounterfactualResult comparing baseline vs modified.
    """
    from app.services.capacity_aware_mrp import (
        run_capacity_aware_mrp, dixon_silver_capacity_feasible,
        build_resource_profile, compute_work_center_load,
    )

    # Baseline run
    baseline = await run_capacity_aware_mrp(db, mps_id)

    # Modified: increase target WC's effective capacity
    wcs = (await db.execute(
        select(WorkCenter).where(WorkCenter.is_active == True)
    )).scalars().all()

    # We can't actually mutate the DB; simulate by giving the target WC
    # an inflated efficiency factor in a copy
    class _MockWC:
        def __init__(self, src, eff):
            self.id = src.id
            self.code = src.code
            self.efficiency = eff
            self.capacity_per_day = src.capacity_per_day
            self.alternate_group = src.alternate_group

    modified_wcs = {}
    for wc in wcs:
        if wc.id == work_center_id:
            modified_wcs[wc.id] = _MockWC(wc, (wc.efficiency or 1.0) * multiplier)
        else:
            modified_wcs[wc.id] = wc

    # Re-run Dixon-Silver with mutated capacity
    # We need planned orders — extract from baseline's MRP items
    from app.models.mps_mrp import MrpItem
    mrp_items = (await db.execute(
        select(MrpItem)
        .where(MrpItem.mrp_master_id ==
               # latest run from baseline pipeline
               (await db.execute(
                   select(MrpMaster.id).where(MrpMaster.mps_master_id == mps_id)
                   .order_by(MrpMaster.created_at.desc())
               )).scalar_one_or_none()
              )
    )).scalars().all()

    # Aggregate planned receipts by part → planned_orders[part_id][t]
    unique_periods = sorted({i.period for i in mrp_items})
    period_to_idx = {p: i for i, p in enumerate(unique_periods)}
    planned: Dict[str, List[float]] = {}
    for it in mrp_items:
        if it.part_id not in planned:
            planned[it.part_id] = [0.0] * len(unique_periods)
        planned[it.part_id][period_to_idx[it.period]] += it.planned_order_receipt

    # Translate to product-keyed for capacity calc
    products = (await db.execute(select(Product))).scalars().all()
    parts = (await db.execute(select(Part))).scalars().all()
    pno_to_pid = {p.product_no: p.id for p in products}
    part_to_prod: Dict[str, str] = {}
    for pt in parts:
        if pt.part_no in pno_to_pid:
            part_to_prod[pt.id] = pno_to_pid[pt.part_no]

    by_prod: Dict[str, List[float]] = {}
    for part_id, qts in planned.items():
        prod_id = part_to_prod.get(part_id)
        if prod_id is None:
            continue
        if prod_id not in by_prod:
            by_prod[prod_id] = [0.0] * len(qts)
        for t, q in enumerate(qts):
            by_prod[prod_id][t] += q

    profile = await build_resource_profile(db)

    # Run Dixon-Silver with modified capacity
    _adjusted, modified = dixon_silver_capacity_feasible(
        by_prod, profile, modified_wcs,
        horizon_periods=max(12, len(unique_periods)),
    )

    # Compute deltas
    delta_holding = modified.holding_cost_penalty - baseline.holding_cost_penalty

    summary = (
        f"WC {work_center_id} 產能 ×{multiplier}：超載期數 "
        f"{len(baseline.overloads)} → {len(modified.overloads)}；"
        f"不可行期數 {len(baseline.infeasible_periods)} → "
        f"{len(modified.infeasible_periods)}；"
        f"持有成本懲罰變化 {delta_holding:+.2f}"
    )

    return CounterfactualResult(
        scenario_name=f"capacity_{work_center_id}_x{multiplier:g}",
        baseline_overload_count=len(baseline.overloads),
        modified_overload_count=len(modified.overloads),
        baseline_infeasible_count=len(baseline.infeasible_periods),
        modified_infeasible_count=len(modified.infeasible_periods),
        holding_cost_delta=delta_holding,
        summary=summary,
    )
